version: '3.8'
services:
  client:
    container_name: client
    build:
      context: ./client
      target: development
    command: pnpm run dev

    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'

  server:
    container_name: server
    build:
      context: ./server
      target: development
    command: pnpm run start:dev
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./server/.env.local.dev

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db/test_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
